### ISSUE TITLE
Failed to generate openapi documentation on pydantic 2.5.0+

### ISSUE THREAD

**Issue by pohmelie** [jefersondaniel/pydantic-mongo#48]
`pydantic` version 2.4.0 works fine with `pydantic-mongo` 2.0.3, but `pydantic` 2.5.0+ broken:
<details> 

``` bash
[2023-11-29 15:40:21 +0400] [426308] [INFO] Running on http://0.0.0.0:8000 (CTRL + C to quit)
[2023-11-29 15:40:23 +0400] [426308] [ERROR] Error in ASGI Framework
Traceback (most recent call last):
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/hypercorn/asyncio/task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/fastapi/applications.py", line 1061, in openapi
    return JSONResponse(self.openapi())
                        ^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/fastapi/applications.py", line 1033, in openapi
    self.openapi_schema = get_openapi(
                          ^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/fastapi/openapi/utils.py", line 475, in get_openapi
    field_mapping, definitions = get_definitions(
                                 ^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/fastapi/_compat.py", line 227, in get_definitions
    field_mapping, definitions = schema_generator.generate_definitions(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 377, in generate_definitions
    self.generate_inner(schema)
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 526, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/main.py", line 603, in __get_pydantic_json_schema__
    return __handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 526, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 212, in modify_model_json_schema
    json_schema = handler(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 1323, in model_schema
    json_schema = self.generate_inner(schema['schema'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 1415, in model_fields_schema
    json_schema = self._named_required_fields_schema(named_required_fields)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 1226, in _named_required_fields_schema
    field_json_schema = self.generate_inner(field).copy()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 544, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2012, in json_schema_update_func
    json_schema = {**handler(core_schema_or_field), **json_schema_update}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 1294, in model_field_schema
    return self.generate_inner(schema['schema'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 1177, in json_or_python_schema
    return self.generate_inner(schema['json_schema'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 1143, in chain_schema
    return self.generate_inner(schema['steps'][step_index])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 956, in function_plain_schema
    return self._function_schema(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 921, in _function_schema
    return self.handle_invalid_for_json_schema(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/poh/.pyenv/versions/dispatcher/lib/python3.12/site-packages/pydantic/json_schema.py", line 2074, in handle_invalid_for_json_schema
    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'no-info', 'function': <bound method ObjectIdField.validate of <class 'pydantic_mongo.fields.ObjectIdField'>>})
```

</details>

**Comment by Artucuno** [comment]
Fixed in #45!

**Comment by pohmelie** [comment]
Should I close this (did not check fix though)

**Comment by pohmelie** [comment]
I checked this out. Code from #45 works fine.
